(()=>{'use strict';
const activities=window.WWM_ACTIVITIES||[], $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={period:'Daily',goal:'role',guild:'all',priority:'all',search:'',hide:false,sort:'default',direction:1};
const RANK={高:3,中:2,低:1}, TIME_RANK={'极低':1,'低':2,'中':3,'高':4,'不定，通常久':5};
const bjParts=(d=new Date())=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
function effectiveDate(){const p=bjParts();return new Date(Date.UTC(+p.year,+p.month-1,+p.day,+p.hour-5))}
function resetKey(period){const d=effectiveDate();if(period==='Daily')return d.toISOString().slice(0,10);if(period==='Monthly')return d.toISOString().slice(0,7);const since=(d.getUTCDay()-1+7)%7;return new Date(d.getTime()-since*864e5).toISOString().slice(0,10)}
function storage(){try{return JSON.parse(localStorage.getItem('wwm-checklist-v1')||'{}')}catch{return {}}}
function isDone(a){return !!storage()[`${a.period}:${resetKey(a.period)}:${a.id}`]}
function setDone(a,v){const s=storage(),k=`${a.period}:${resetKey(a.period)}:${a.id}`;v?s[k]=true:delete s[k];localStorage.setItem('wwm-checklist-v1',JSON.stringify(s))}
function currentPriority(a){return a.priority[state.goal]}
function inPeriod(a){return state.period==='Daily'?a.period==='Daily':a.period==='Weekly'||a.period==='Monthly'}
function timeLevel(a){return a.time.startsWith('不定')?'不定，通常久':a.time.split('（')[0].trim()}
function defaultCompare(a,b){return Number(isDone(a))-Number(isDone(b))||RANK[currentPriority(b)]-RANK[currentPriority(a)]||a.category.localeCompare(b.category,'zh-CN')||a.name.localeCompare(b.name,'zh-CN')}
function compareActivities(a,b){if(state.sort==='default')return defaultCompare(a,b);let n=0;if(state.sort==='completion')n=Number(isDone(a))-Number(isDone(b));else if(state.sort==='priority')n=RANK[currentPriority(b)]-RANK[currentPriority(a)];else if(state.sort==='time')n=TIME_RANK[timeLevel(a)]-TIME_RANK[timeLevel(b)];else if(state.sort==='category')n=a.category.localeCompare(b.category,'zh-CN');else n=a.name.localeCompare(b.name,'zh-CN');return n*state.direction||defaultCompare(a,b)}
function filtered(){return activities.filter(a=>inPeriod(a)&&(state.guild==='all'||a.guild===(state.guild==='yes'))&&(state.priority==='all'||currentPriority(a)===state.priority)&&(!state.hide||!isDone(a))&&(!state.search||a.rewards.toLowerCase().includes(state.search))).sort(compareActivities)}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function nameHtml(a){const n=escapeHtml(a.name);return a.link?`<a href="${a.link}">${n}</a>`:n}
function timeHtml(a){const l=escapeHtml(timeLevel(a)),n=escapeHtml(a.time.slice(timeLevel(a).length));return `<span class="time-level">${l}</span>${n?` <span class="time-note">${n}</span>`:''}`}
function sortMark(key){return state.sort===key?(state.direction===1?' ↑':' ↓'):' ↕'}
function syncSortSelect(){const el=$('#sort-select');if(el)el.value=state.sort==='default'?'default':`${state.sort}-${state.direction===1?'asc':'desc'}`}
function render(){const rows=filtered();$('#activity-list').innerHTML=`<div class="activity-head"><button data-sort="completion" aria-label="按完成状态排序">完成${sortMark('completion')}</button><button data-sort="name" aria-label="按活动名称排序">活动${sortMark('name')}</button><button data-sort="category" aria-label="按活动类别排序">类别${sortMark('category')}</button><button data-sort="priority" aria-label="按优先级排序">优先级${sortMark('priority')}</button><span>主要奖励 / 目标</span><button data-sort="time" aria-label="按用时排序">用时${sortMark('time')}</button><span></span></div>`+rows.map(a=>`<div class="activity-row ${isDone(a)?'done':''}" data-id="${a.id}"><input class="check" type="checkbox" ${isDone(a)?'checked':''} aria-label="标记${escapeHtml(a.name)}完成"><div><div class="activity-name">${nameHtml(a)}</div><div class="badges">${a.period==='Monthly'?'<span class="badge period-badge">每月</span>':''}${a.guild?'<span class="badge guild">百业活跃</span>':''}</div></div><div class="activity-category">${escapeHtml(a.category)}</div><div><span class="priority ${currentPriority(a)==='高'?'high':currentPriority(a)==='中'?'medium':'low'}">${currentPriority(a)}</span></div><div class="reward">${escapeHtml(a.rewards)}</div><div class="guide">${timeHtml(a)}</div><button class="details" aria-label="展开详情" aria-expanded="false">⌄</button><div class="activity-detail"><p><strong>做法 / 攻略</strong><br>${escapeHtml(a.guide||'暂无')}</p><p><strong>备注</strong><br>${escapeHtml(a.notes||'暂无')}</p></div></div>`).join('');$('#empty-state').hidden=rows.length>0;updateProgress();syncSortSelect()}
function group(p){return activities.filter(a=>p==='Daily'?a.period==='Daily':a.period!=='Daily')}
function updateProgress(){const d=group('Daily'),r=group('Recurring');$('#daily-count').textContent=`${d.filter(isDone).length}/${d.length}`;$('#recurring-count').textContent=`${r.filter(isDone).length}/${r.length}`;const all=group(state.period),done=all.filter(isDone).length;$('#progress-label').textContent=state.period==='Daily'?'今日进度':'本周 / 本月进度';$('#progress-text').textContent=`${done} / ${all.length}`;$('#progress-bar').style.width=(all.length?done/all.length*100:0)+'%'}
function clock(){const p=bjParts();$('#beijing-time').textContent=`北京时间 ${p.hour}:${p.minute}`;$('#next-reset').textContent=state.period==='Daily'?'每日 05:00 重置':'每周一 / 每月1日 05:00 重置'}
function defaultDirection(key){return key==='priority'?1:1}
$('#activity-list').addEventListener('click',e=>{if(e.target.dataset.sort){const key=e.target.dataset.sort;state.direction=state.sort===key?-state.direction:defaultDirection(key);state.sort=key;render();return}const row=e.target.closest('.activity-row');if(!row)return;const a=activities.find(x=>x.id===row.dataset.id);if(e.target.matches('.check')){setDone(a,e.target.checked);render()}else if(e.target.matches('.details')){row.classList.toggle('expanded');e.target.setAttribute('aria-expanded',row.classList.contains('expanded'));e.target.textContent=row.classList.contains('expanded')?'⌃':'⌄'}});
$$('.period-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.period-tabs button').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');state.period=b.dataset.period;render();clock()}));
$('#goal-filter').addEventListener('change',e=>{state.goal=e.target.value;render()});
$('#guild-filter').addEventListener('change',e=>{state.guild=e.target.value;render()});
$('#priority-filter').addEventListener('change',e=>{state.priority=e.target.value;render()});
$('#sort-select').addEventListener('change',e=>{if(e.target.value==='default'){state.sort='default';state.direction=1}else{const [key,order]=e.target.value.split('-');state.sort=key;state.direction=order==='asc'?1:-1}render()});
$('#search').addEventListener('input',e=>{state.search=e.target.value.trim().toLowerCase();$$('.quick-search button').forEach(b=>b.classList.toggle('active',b.textContent===e.target.value));render()});
$('#hide-completed').addEventListener('change',e=>{state.hide=e.target.checked;render()});
$$('.quick-search button').forEach(b=>b.addEventListener('click',()=>{$('#search').value=$('#search').value===b.textContent?'':b.textContent;state.search=$('#search').value.toLowerCase();$$('.quick-search button').forEach(x=>x.classList.toggle('active',x===b&&!!state.search));render()}));
function route(){const id=location.hash.slice(1)||'checklist';$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav a').forEach(x=>x.classList.toggle('active',x.hash==='#'+id));$('#main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}
window.addEventListener('hashchange',route);$('.menu-toggle').addEventListener('click',e=>{const open=$('#main-nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});
const articles={energy:{category:'养成策略',title:'心力消耗策略',text:'心力溢出会造成资源浪费，建议优先安排消耗心力的玩法。以下为原始知识图。',img:'assets/心力消耗策略.png',author:'童聪',authorUrl:'https://space.bilibili.com/456111385',source:'https://www.bilibili.com/video/BV1vdr5BiE5j/'},craft:{category:'百科知识',title:'天工知识',text:'天工相关资料与速查说明。以下为原始知识图。',img:'assets/天工知识.png',author:'林恩恩恩恩恩恩',authorUrl:'https://space.bilibili.com/431593381',source:'https://www.bilibili.com/video/BV1u6sKz2Efc'}};
$$('[data-article]').forEach(b=>b.addEventListener('click',()=>{const a=articles[b.dataset.article];$$('.tree-child').forEach(x=>x.classList.toggle('active',x.dataset.article===b.dataset.article));$('#knowledge-article').innerHTML=`<p class="eyebrow">${a.category}</p><h1>${a.title}</h1><p>${a.text}</p><figure><img src="${a.img}" alt="${a.title}知识图" loading="lazy"><figcaption>作者：<a href="${a.authorUrl}" target="_blank" rel="noopener noreferrer">${a.author}</a> · <a href="${a.source}" target="_blank" rel="noopener noreferrer">查看来源</a></figcaption></figure>`}));
route();render();clock();setInterval(clock,60000);
})();
