(()=>{'use strict';
const activities=window.WWM_ACTIVITIES||[], $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], limitedSource=window.WWM_LIMITED_EVENTS;let limitedEvents=limitedSource?.events?.map(a=>({...a,period:'Limited'}))||[],eventsLoaded=true,eventsLoadError=!limitedSource;
const state={period:'Daily',goal:'role',priority:'all',search:'',hide:false,sort:'default',direction:1};
const RANK={高:3,中:2,低:1}, TIME_RANK={'极低':1,'低':2,'中':3,'高':4,'不定，通常久':5};
const bjParts=(d=new Date())=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
function effectiveDate(){const p=bjParts();return new Date(Date.UTC(+p.year,+p.month-1,+p.day,+p.hour-5))}
function resetKey(period){const d=effectiveDate();if(period==='Daily')return d.toISOString().slice(0,10);if(period==='Monthly')return d.toISOString().slice(0,7);const since=(d.getUTCDay()-1+7)%7;return new Date(d.getTime()-since*864e5).toISOString().slice(0,10)}
function storage(){try{return JSON.parse(localStorage.getItem('wwm-checklist-v1')||'{}')}catch{return {}}}
function completionKey(a){if(a.period!=='Limited')return resetKey(a.period);const r=a.completionReset||{};if(r.type==='daily')return resetKey('Daily');if(r.type==='weekly')return resetKey('Weekly');if(r.type==='once'&&r.at)return `${Date.now()<Date.parse(r.at)?'before':'after'}:${r.at}`;return 'event'}
function isDone(a){return !!storage()[`${a.period}:${completionKey(a)}:${a.id}`]}
function setDone(a,v){const s=storage(),k=`${a.period}:${completionKey(a)}:${a.id}`;v?s[k]=true:delete s[k];localStorage.setItem('wwm-checklist-v1',JSON.stringify(s))}
function currentPriority(a){return a.priority[state.goal]}
function inPeriod(a){if(state.period==='Limited')return a.period==='Limited';return state.period==='Daily'?a.period==='Daily':a.period==='Weekly'||a.period==='Monthly'}
function timeLevel(a){return a.time.startsWith('不定')?'不定，通常久':a.time.split(/（|\s*\(/)[0].trim()}
function defaultCompare(a,b){return Number(isDone(a))-Number(isDone(b))||RANK[currentPriority(b)]-RANK[currentPriority(a)]||a.category.localeCompare(b.category,'zh-CN')||a.name.localeCompare(b.name,'zh-CN')}
function compareActivities(a,b){if(state.sort==='default')return defaultCompare(a,b);let n=0;if(state.sort==='completion')n=Number(isDone(a))-Number(isDone(b));else if(state.sort==='priority')n=RANK[currentPriority(b)]-RANK[currentPriority(a)];else if(state.sort==='time')n=TIME_RANK[timeLevel(a)]-TIME_RANK[timeLevel(b)];else if(state.sort==='category')n=a.category.localeCompare(b.category,'zh-CN');else n=a.name.localeCompare(b.name,'zh-CN');return n*state.direction||defaultCompare(a,b)}
function activeLimitedEvents(){return limitedEvents.filter(a=>Date.now()<Date.parse(a.expirationDate))}
function sourceActivities(){return state.period==='Limited'?activeLimitedEvents():activities}
function filtered(){return sourceActivities().filter(a=>inPeriod(a)&&(state.priority==='all'||currentPriority(a)===state.priority)&&(!state.hide||!isDone(a))&&(!state.search||a.rewards.toLowerCase().includes(state.search))).sort(compareActivities)}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function nameHtml(a){const n=escapeHtml(a.name);return a.link?`<a href="${a.link}">${n}</a>`:n}
function timeHtml(a){const l=escapeHtml(timeLevel(a)),n=escapeHtml(a.time.slice(timeLevel(a).length));return `<span class="time-level">${l}</span>${n?` <span class="time-note">${n}</span>`:''}`}
function deadlineHtml(a){const ms=Date.parse(a.expirationDate)-Date.now(),days=Math.ceil(ms/864e5),level=days<=3?'urgent':days<=7?'soon':'';const text=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(a.expirationDate));return `<div class="deadline ${level}"><strong>${text}</strong><small>${days<=1?'不足 1 天':`剩余 ${days} 天`}</small></div>`}
function sortMark(key){return state.sort===key?(state.direction===1?' ↑':' ↓'):' ↕'}
function render(){const rows=filtered(),limited=state.period==='Limited',list=$('#activity-list');list.classList.toggle('limited',limited);list.innerHTML=`<div class="activity-head"><button data-sort="completion" aria-label="按完成状态排序">完成${sortMark('completion')}</button><span>活动</span><button data-sort="category" aria-label="按活动类别排序">类别${sortMark('category')}</button><button data-sort="priority" aria-label="按优先级排序">优先级${sortMark('priority')}</button><span>主要奖励 / 目标</span><button data-sort="time" aria-label="按用时排序">用时${sortMark('time')}</button>${limited?'<span>截止日期</span>':''}<span></span></div>`+rows.map(a=>`<div class="activity-row ${isDone(a)?'done':''}" data-id="${a.id}"><input class="check" type="checkbox" ${isDone(a)?'checked':''} aria-label="标记${escapeHtml(a.name)}完成"><div><div class="activity-name">${nameHtml(a)}</div><div class="badges">${a.period==='Monthly'?'<span class="badge period-badge">每月</span>':''}${a.guild?'<span class="badge guild">百业活跃</span>':''}</div></div><div class="activity-category">${escapeHtml(a.category)}</div><div><span class="priority ${currentPriority(a)==='高'?'high':currentPriority(a)==='中'?'medium':'low'}">${currentPriority(a)}</span></div><div class="reward">${escapeHtml(a.rewards)}</div><div class="guide">${timeHtml(a)}</div>${limited?deadlineHtml(a):''}<button class="details" aria-label="展开详情" aria-expanded="false">⌄</button><div class="activity-detail"><p><strong>做法 / 攻略</strong><br>${escapeHtml(a.guide||'暂无')}</p><p><strong>备注</strong><br>${escapeHtml(a.notes||'暂无')}</p></div></div>`).join('');const empty=$('#empty-state');empty.textContent=limited&&!eventsLoaded?'正在载入限时活动…':limited&&eventsLoadError?'限时活动载入失败，请刷新页面重试。':'没有符合当前筛选条件的活动。';empty.classList.toggle('load-error',limited&&eventsLoadError);empty.hidden=rows.length>0;updateProgress()}
function group(p){if(p==='Limited')return activeLimitedEvents();return activities.filter(a=>p==='Daily'?a.period==='Daily':a.period!=='Daily')}
function updateProgress(){const l=group('Limited'),d=group('Daily'),r=group('Recurring');$('#limited-count').textContent=`${l.filter(isDone).length}/${l.length}`;$('#daily-count').textContent=`${d.filter(isDone).length}/${d.length}`;$('#recurring-count').textContent=`${r.filter(isDone).length}/${r.length}`;const all=group(state.period),done=all.filter(isDone).length;$('#progress-label').textContent=state.period==='Limited'?'限时活动进度':state.period==='Daily'?'今日进度':'本周 / 本月进度';$('#progress-text').textContent=`${done} / ${all.length}`;$('#progress-bar').style.width=(all.length?done/all.length*100:0)+'%'}
function clock(){const p=bjParts();$('#beijing-time').textContent=`北京时间 ${p.hour}:${p.minute}`;$('#next-reset').textContent=state.period==='Limited'?'完成状态按各活动规则重置':state.period==='Daily'?'每日 05:00 重置':'每周一 / 每月1日 05:00 重置'}
function defaultDirection(key){return key==='priority'?1:1}
$('#activity-list').addEventListener('click',e=>{if(e.target.dataset.sort){const key=e.target.dataset.sort;state.direction=state.sort===key?-state.direction:defaultDirection(key);state.sort=key;render();return}const row=e.target.closest('.activity-row');if(!row)return;const a=[...activities,...limitedEvents].find(x=>x.id===row.dataset.id);if(e.target.matches('.check')){setDone(a,e.target.checked);render()}else if(e.target.matches('.details')){row.classList.toggle('expanded');e.target.setAttribute('aria-expanded',row.classList.contains('expanded'));e.target.textContent=row.classList.contains('expanded')?'⌃':'⌄'}});
$$('.period-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.period-tabs button').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');state.period=b.dataset.period;render();clock()}));
$('#goal-filter').addEventListener('change',e=>{state.goal=e.target.value;render()});
$('#priority-filter').addEventListener('change',e=>{state.priority=e.target.value;render()});
$('#search').addEventListener('input',e=>{state.search=e.target.value.trim().toLowerCase();$$('.quick-search button').forEach(b=>b.classList.toggle('active',b.textContent===e.target.value));render()});
$('#hide-completed').addEventListener('change',e=>{state.hide=e.target.checked;render()});
$$('.quick-search button').forEach(b=>b.addEventListener('click',()=>{$('#search').value=$('#search').value===b.textContent?'':b.textContent;state.search=$('#search').value.toLowerCase();$$('.quick-search button').forEach(x=>x.classList.toggle('active',x===b&&!!state.search));render()}));
function route(){const [requestedPage,requestedArticle]=location.hash.slice(1).split('/'),id=document.getElementById(requestedPage)?requestedPage:'checklist';$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('#main-nav a').forEach(x=>x.classList.toggle('active',x.hash==='#'+id));if(id==='knowledge')renderKnowledge(articles[requestedArticle]?requestedArticle:'energy');if(id==='guild')renderGuild(['activity','perks'].includes(requestedArticle)?requestedArticle:'activity');if(id==='must-do')renderMust(['hexi-glass','merchants'].includes(requestedArticle)?requestedArticle:'hexi-glass');$('#main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}
window.addEventListener('hashchange',route);$('.menu-toggle').addEventListener('click',e=>{const open=$('#main-nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});
const shopRows=[
['赛季商店（不肝商店） - 赛季追赶','通宝','每周刷新','image20.png','长期每周必买'],
['赛季商店-战斗养成','啸玉 （当前阶的叠音材料）','每周刷新，剩余库存不清空','image10.png','长期每周必买'],
['赛季商店-战斗养成','金丝钱袋（通宝）','每周刷新','image23.png','清空体力的主要方式'],
['赛季商店-战斗养成','一盒短陌钱','每周刷新','image12.png','后期如果斗蛐蛐，开封跑商的话不需要买'],
['赛季商店-战斗养成','心法箱子','每周刷新','image21.png','长期每周必买'],
['赛季商店-战斗养成','武学心得','每周刷新','image19.png','长期每周必买'],
['赛季商店-战斗养成','奇术支援箱','每周刷新','image15.png','不想肝奇术升级'],
['赛季商店-装备宝匣','当前阶的装备匣','每周刷新','image3.png','么玉充足，缺装备的时候'],
['赛季商店-金装兑换','当前阶的转律石','每周刷新','image14.png','长期每周必买'],
['赛季商店-金装兑换','当前阶的金妙音石','每周刷新','image16.png','长期每周必买'],
['赛季商店-金装兑换','当前阶的金装自选匣','每周补货，有库存上限','image4.png','能买就买'],
['赛季商店-营生养成','营生手记','每周刷新','image13.png','能买就买，需要提升悬壶/文士的等级来解锁高阶的药品/符帖来提升战斗能力。'],
['赛季商店-外观兑换','袅袅之音','每周刷新','image5.png','度过新手期，买完易水歌之后，可以开始买。'],
['社交商店-江湖行商店','当前阶的止戈定音石','每周刷新','image27.png','按需购买。不玩止戈(pvp)或者百业战可以忽略。'],
['社交商店-江湖行商店','当前阶的止戈变音石','每周刷新','image11.png','按需购买。不玩止戈(pvp)或者百业战可以忽略。'],
['百业-赤金小铺','绕梁之音','每月刷新','image2.png','不换白不换，可以抽外观。'],
['传承商店','奇术支援箱','每周刷新','image29.png','长期每周必买'],
['传承商店','当前阶的变音石','每周补货，剩余库存不清空','image22.png','长期每周必买'],
['传承商店','心法箱子','每周刷新','image8.png','长期每周必买'],
['不错小店','通宝','每周刷新','image25.png','缺通宝可以买'],
['战令商店','当前阶的转律石','每周刷新','image24.png','长期每周必买。注意看准描述是几阶的，别买错了（痛的教训）。因为战令商店所有转律石都有，乱序的。'],
['战令商店','当前阶的变音石','每周刷新','image18.png','同上'],
['战令商店','奇术支援箱','每周刷新','image7.png','长期每周必买'],
['战令商店','不错鸟羽','每期战令刷新','image17.png','建议买。可以到不错小店兑换外观，通宝。'],
['战令商店','等级上限帖','每期战令刷新','image6.png','只有购买了战令的才有意义买。'],
['商店->精选->礼包','通宝','每周刷新','image26.png','免费，记得领'],
['商店->精选->道具->江湖百珍','袅袅之音','每周刷新','image30.png','度过新手期，买完易水歌之后，可以开始买。'],
['商店->和鸣->天精商店','袅袅之音','没有库存限制','image9.png','需要消耗天精。天精是和鸣消耗袅袅之音抽外观时会获得的。'],
['商店->和鸣->地华商店','袅袅之音','每月刷新','image1.png','需要消耗地华。地华是和鸣消耗绕梁之音抽普通外观获得的。'],
['商店->和鸣->地华商店','折音券','每月刷新','image28.png','需要消耗地华。地华是和鸣消耗绕梁之音抽普通外观获得的。如果你需要用长鸣珠（充值/氪金）买外观，有券在手，花钱更少。']
];
function shopTable(){return `<div class="shop-table-wrap"><table class="shop-table"><thead><tr><th>商店</th><th>物品</th><th>刷新频率</th><th>图标</th><th>备注</th></tr></thead><tbody>${shopRows.map(r=>`<tr><td>${escapeHtml(r[0])}</td><td><strong>${escapeHtml(r[1])}</strong></td><td>${escapeHtml(r[2])}</td><td><img src="assets/百科查阅/养成策略/商店必买攻略/${r[3]}" alt="${escapeHtml(r[1])}图标" loading="lazy"></td><td>${escapeHtml(r[4])}</td></tr>`).join('')}</tbody></table></div>`}
const fireOilBlueprints=[['SHARE282eb5dc7c6c5ad0','image22.png','约982原木'],['SHARE13b547403c84966d','image20.png','约1000原木'],['SHAREd12b08b957e24afc','image21.png','约491原木'],['SHARE44e08c8829845723','image29.png','约864原木'],['SHAREff0c0c92c61e0ec4','image17.png','约196原木']];
const fireOilSteps=[['1','打开菜单，点击“外观”','image2.png','打开菜单中的外观'],['2','点击右边“万相集”','image11.png','进入万相集'],['3','选择左边的“建造”，找不到可以上下滚动一下。','image27.png','选择建造分类'],['4','右上角搜索栏填入图纸分享码','image9.png','搜索图纸分享码'],['5','点击进入搜索出来的图纸（应该只有一个搜索结果，点进去），点击“获取图纸”','image19.png','获取图纸'],['6','可以重复步骤1~5搜索到图纸之后，再点击“套用图纸”。（或者进入建造模式，在你的图纸背包里找到刚刚获取的图纸）','image18.png','获取图纸后套用图纸'],['7','点击“原位摆放”','image16.png','选择原位摆放'],['8','如果出现距离原摆放位置过远的提示，选择“前往”。此时会弹出地图，并且有黄圈显示图纸所在范围，可以自行传送并且走到图纸范围。','image25.png','前往图纸所在范围'],['9','进入范围后重复以上步骤进行“原位摆放”。此时会逐渐摆好蓝色的虚影。结束后，靠近蓝色虚影，会出现对应图纸名字的交互选项，如右图。','image28.png','靠近图纸蓝色虚影'],['10','交互选择“自动落成”。等待图纸自动填充完成。','image6.png','选择自动落成'],['11','把所有的采火大道图纸按照同样的方式自动落成造好。测试通过没有问题，可进行后续步骤。','',''],['12','完成后，可再靠近造好的大道，同样出现交互选项，选择“移除图纸”','image12.png','选择移除图纸'],['13','选择“仅移除图纸轮廓”。这样之后采火的时候不会意外触发图纸交互选项。','image5.png','仅移除图纸轮廓']];
const fireOilImage=(name,alt)=>`<img class="content-thumbnail" data-zoomable src="assets/百科查阅/护肝攻略/单人世界采集火油方法/${name}" alt="${alt}" loading="lazy">`;
function fireOilHtml(){return `<p class="eyebrow">护肝攻略</p><h1>国际服单人世界采集火油方法</h1><div class="intro-image-row">${fireOilImage('image23.png','早期的天工火')}<p>（早期的天工火，附着在武器上增加气血伤害）</p>${fireOilImage('image24.png','不见山之后解锁的高级天工火')}<p>（不见山之后解锁的高级天工火，需要2火油+1毒或者2火油+1水制造）</p></div><p>缺天工火？缺火油造高级的特殊淬火油？那么来看看这个攻略，希望能帮助到你。</p><nav class="article-toc bullet-toc" aria-label="采集火油攻略章节"><strong>本页目录</strong><ul><li><button type="button" data-scroll-target="fire-oil-foluo">采集佛泪参</button></li><li><button type="button" data-scroll-target="fire-oil-braziers">单人世界手动采集火盆</button></li><li><button type="button" data-scroll-target="fire-oil-road">单人世界建造采火大道</button><ul><li><button type="button" data-scroll-target="fire-oil-blueprints">图纸码分享</button></li><li><button type="button" data-scroll-target="fire-oil-build">建造流程</button></li></ul></li></ul></nav><p class="zoom-hint">⌕ 所有图片均可双击放大；也可聚焦图片后按 Enter 查看原图。</p>
<section class="guide-article-section" id="fire-oil-foluo"><h2>采集佛泪参</h2><p>可以在单人世界或者多人世界采集佛泪参，佛泪参有几处密集生长点，可以每天去看看。而且佛泪参有几率掉落佛泪须，是很多奇术的升级材料。但是多人世界比较难抢到。</p><div class="content-image-grid">${fireOilImage('image14.png','佛泪参密集生长点一')}${fireOilImage('image7.png','佛泪参密集生长点二')}${fireOilImage('image3.png','佛泪参密集生长点三')}${fireOilImage('image13.png','佛泪参采集位置')}</div></section>
<section class="guide-article-section" id="fire-oil-braziers"><h2>单人世界手动采集火盆</h2><p>下图所示的火盆可以采集到1~3个淬火油。</p><div class="content-image-grid">${fireOilImage('image10.png','可采集淬火油的火盆')}</div><p>以下这些地点（按照由多到少排序）可以比较密集采集到火油：</p><ol class="location-list"><li><p>开封天上来。整个天上来都是火盆，可以从赤龙堂界碑开始绕圈走，用“听风辨位”搜索还没采集的火盆。</p>${fireOilImage('image15.png','开封天上来采集路线')}</li><li><p>开封白马驿界碑附近，大家都在用火盆烧纸钱。</p>${fireOilImage('image8.png','开封白马驿火盆位置')}</li><li><p>清河丰和村村尾（箭头所在）</p>${fireOilImage('image26.png','清河丰和村村尾火盆位置')}</li><li><p>清河别馆前山传送点，沿着箭头方向一路上山都有火盆，还有绣金楼黑衣人陪你玩耍。</p>${fireOilImage('image1.png','清河别馆前山火盆路线')}</li><li><p>清河佛爷寨，从传送点到据点之前有6个火盆，可以一路shift安心采。</p>${fireOilImage('image4.png','清河佛爷寨火盆路线')}</li></ol></section>
<section class="guide-article-section" id="fire-oil-road"><h2>单人世界建造采火大道</h2><p>如果你有购买采集马，有采集足够的木材的话，可以参考以下方法建造“采火大道”。造好之后就可以骑着采集马快速采集啦。</p><h3 id="fire-oil-blueprints">图纸码分享</h3><div class="guide-table-wrap"><table class="guide-table"><thead><tr><th>分享码</th><th>图片</th><th>作者</th><th>耗材</th></tr></thead><tbody>${fireOilBlueprints.map(r=>`<tr><td><code>${r[0]}</code></td><td>${fireOilImage(r[1],`采火大道图纸 ${r[0]}`)}</td><td>ShinyLatias</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div><h3 id="fire-oil-build">建造流程</h3><div class="build-steps">${fireOilSteps.map(r=>`<section><span>${r[0]}</span><p>${r[1]}</p>${r[2]?fireOilImage(r[2],r[3]):''}${r[0]==='6'?'<small>（获取图纸之后，按钮变成套用图纸）</small>':''}</section>`).join('')}</div></section>`}
const articles={energy:{category:'养成策略',title:'心力消耗策略',text:'心力溢出会造成资源浪费，建议优先安排消耗心力的玩法。以下为原始知识图。',img:'assets/百科查阅/养成策略/心力消耗策略.png',author:'童聪',authorUrl:'https://space.bilibili.com/456111385',source:'https://www.bilibili.com/video/BV1vdr5BiE5j/'},craft:{category:'百科知识',title:'天工知识',text:'天工相关资料与速查说明。以下为原始知识图。',img:'assets/百科查阅/养成策略/天工知识.png',author:'林恩恩恩恩恩恩',authorUrl:'https://space.bilibili.com/431593381',source:'https://www.bilibili.com/video/BV1u6sKz2Efc'},shop:{category:'养成策略',title:'每周商店必买攻略',text:'不知道什么该买？萌新们可以参考这个必买攻略，确保自己至少每个该买的商店都逛过了 😀。商店里面其他物品可以按需购买。',table:true},'fire-oil':{category:'护肝攻略',title:'国际服单人世界采集火油方法',custom:true}};
function renderKnowledge(key){const a=articles[key];$$('#knowledge .tree-child[data-article]').forEach(x=>x.classList.toggle('active',x.dataset.article===key));$('#knowledge-article').innerHTML=a.custom?fireOilHtml():`<p class="eyebrow">${a.category}</p><h1>${a.title}</h1><p>${a.text}</p>${a.table?shopTable():`<figure><img src="${a.img}" alt="${a.title}知识图" loading="lazy"><figcaption>作者：<a href="${a.authorUrl}" target="_blank" rel="noopener noreferrer">${a.author}</a> · <a href="${a.source}" target="_blank" rel="noopener noreferrer">查看来源</a></figcaption></figure>`}`;bindZoomables($('#knowledge-article'))}
function navigate(page,article){const hash=`#${page}/${article}`;location.hash===hash?route():location.hash=hash}
function renderGuild(key){$$('[data-guild-panel]').forEach(x=>x.classList.toggle('active',x.dataset.guildPanel===key));$$('[data-guild-article]').forEach(x=>x.classList.toggle('active',x.dataset.guildArticle===key));window.scrollTo({top:0,behavior:'auto'})}
function renderMust(key){$$('[data-must-panel]').forEach(x=>x.classList.toggle('active',x.dataset.mustPanel===key));$$('[data-must-article]').forEach(x=>x.classList.toggle('active',x.dataset.mustArticle===key));window.scrollTo({top:0,behavior:'auto'})}
$$('[data-article]').forEach(b=>b.addEventListener('click',()=>navigate('knowledge',b.dataset.article)));
$$('[data-guild-article]').forEach(b=>b.addEventListener('click',()=>navigate('guild',b.dataset.guildArticle)));
$$('[data-must-article]').forEach(b=>b.addEventListener('click',()=>navigate('must-do',b.dataset.mustArticle)));
const lightbox=$('#image-lightbox'),lightboxImage=lightbox.querySelector('img'),lightboxCaption=$('#lightbox-caption');
function openMerchantImage(img){lightboxImage.src=img.currentSrc||img.src;lightboxImage.alt=img.alt;lightboxCaption.textContent=img.alt;lightbox.showModal()}
function bindZoomables(scope=document){scope.querySelectorAll('.merchant-gallery img,[data-zoomable]').forEach(img=>{if(img.dataset.zoomBound)return;img.dataset.zoomBound='true';img.tabIndex=0;img.setAttribute('role','button');img.title='双击放大查看';img.addEventListener('dblclick',()=>openMerchantImage(img));img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openMerchantImage(img)}})})}
bindZoomables();document.addEventListener('click',e=>{const button=e.target.closest('[data-scroll-target]');if(!button)return;const target=document.getElementById(button.dataset.scrollTarget);if(target)target.scrollIntoView({behavior:'smooth',block:'start'})});
lightbox.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});lightbox.addEventListener('close',()=>{lightboxImage.src=''});
route();render();clock();setInterval(()=>{clock();if(state.period==='Limited')render()},60000);
})();
